import { NormalizerConfig } from "./types";

/**
 * Generated by src/scripts/calibrateCompatibility.ts — do not hand-edit.
 *
 * Fitted from 200 pairs x 365 days (seed 1592598101).
 *
 * These numbers describe THIS pair of rule tables and THIS set of factors. Re-run the
 * calibration whenever src/modules/compatibilityPeople/rules.ts or ./factors.ts change.
 */

/**
 * How compatible two people are, full stop — the number behind `baseScore`.
 *
 * Fitted on the POOLED distribution across pairs, to land it on score percentiles
 * p10 30 / p90 80. Pooled is right here: this one is a comparison against
 * every other pair, and it is the same for them tomorrow as it is today.
 */
export const BASE_NORMALIZER: NormalizerConfig = { median: 19.44, sigma: 16.99 };

/**
 * How wide the squash opens around a pair's own median — the gain on the daily score.
 *
 * Fitted on DEVIATIONS from each pair's median rather than on the pooled raws, to land
 * a single pair's own year on score percentiles p10 25 / p90 75. Fitting the pooled
 * distribution instead is what produced the flat scores this replaced: most of that
 * spread is the gap BETWEEN pairs, so sigma came out wide enough to swallow everything
 * a single pair's sky does over a year.
 *
 * The median is not here because there is no global one — `calibratePair` measures it
 * per pair. Sigma stays shared so a turbulent pair keeps its turbulence.
 */
export const DAILY_SIGMA = 13.25;
