import { fromNodeHeaders } from "better-auth/node";
import dayjs from "dayjs";
import utc from "dayjs/plugin/utc.js";
import { and, eq } from "drizzle-orm";
import { FastifyPluginAsync } from "fastify";
import { ZodTypeProvider } from "fastify-type-provider-zod";
import { z } from "zod";

import { dailyInsights } from "../../db/schema";
import { auth } from "../../lib/auth";
import { CALIBRATION_VERSION } from "../../modules/dailyScore/calibration";
import { getOrCreateTransits, scoreProfileForDate } from "../../modules/dailyScore/service";
import { ENGINE_VERSION } from "../../modules/dailyScore/version";

dayjs.extend(utc);

const errorSchema = z.object({
    error: z.object({
        code: z.string(),
        message: z.string(),
    }),
});

/**
 * Why a score is what it is.
 *
 * Recomputes rather than reading stored impacts: the engine is deterministic, so a
 * recomputation under the same engine version is identical to what was stored, and
 * keeping 100+ impact rows per user per day would make this the largest table in
 * the database for no gain.
 *
 * If the stored row was written by an older engine, the numbers will differ — that
 * is not a bug, and the response says so explicitly.
 */
export default (async (fastify) => {
    // Not for end users: it exposes the full rule table's effect on a chart.
    if (process.env.NODE_ENV === "production") {
        return;
    }

    fastify.withTypeProvider<ZodTypeProvider>().get(
        "/score/explain",
        {
            schema: {
                querystring: z.object({
                    date: z.string().refine((val) => dayjs.utc(val).isValid(), {
                        message: "Invalid date format",
                    }),
                }),
                response: {
                    200: z.object({ data: z.any() }),
                    401: errorSchema,
                    409: errorSchema,
                    500: errorSchema,
                },
            },
        },
        async (request, reply) => {
            const session = await auth.api.getSession({
                headers: fromNodeHeaders(request.headers),
            });

            if (!session) {
                return reply.status(401).send({
                    error: { code: "unauthorized", message: "User must be logged in to access this resource." },
                });
            }

            if (!session.profile) {
                return reply.status(409).send({
                    error: { code: "profile_required", message: "User must complete onboarding first." },
                });
            }

            try {
                const date = dayjs.utc(request.query.date).format("YYYY-MM-DD");

                const { planets } = await getOrCreateTransits(fastify.db, date);
                const recomputed = scoreProfileForDate(session.profile, planets);

                const [stored] = await fastify.db
                    .select({
                        loveScore: dailyInsights.loveScore,
                        careerScore: dailyInsights.careerScore,
                        healthScore: dailyInsights.healthScore,
                        moodScore: dailyInsights.moodScore,
                        overallScore: dailyInsights.overallScore,
                        rawScores: dailyInsights.rawScores,
                        confidence: dailyInsights.confidence,
                        engineVersion: dailyInsights.engineVersion,
                        calibrationVersion: dailyInsights.calibrationVersion,
                    })
                    .from(dailyInsights)
                    .where(and(eq(dailyInsights.userId, session.user.id), eq(dailyInsights.date, date)))
                    .limit(1);

                const staleEngine = stored != null && stored.engineVersion !== ENGINE_VERSION;
                const staleCalibration = stored != null && stored.calibrationVersion !== CALIBRATION_VERSION;

                return reply.status(200).send({
                    data: {
                        date,
                        engineVersion: ENGINE_VERSION,
                        calibrationVersion: CALIBRATION_VERSION,
                        stored,
                        warning:
                            staleEngine || staleCalibration
                                ? "This score was generated by an older scoring engine, so the recomputed values below will not match the stored ones."
                                : null,
                        recomputed: {
                            scores: recomputed.scores,
                            raw: recomputed.raw,
                            confidence: recomputed.confidence,
                            coveredWeight: recomputed.coveredWeight,
                            unresolved: recomputed.unresolved,
                        },
                        breakdown: recomputed.breakdown,
                        // Every contribution, sorted so the biggest movers read first.
                        impacts: [...recomputed.impacts].sort((a, b) => Math.abs(b.value) - Math.abs(a.value)),
                    },
                });
            } catch (error: unknown) {
                request.log.error({ err: error }, "Failed to explain daily score");

                return reply.status(500).send({
                    error: {
                        code: "error",
                        message: error instanceof Error ? (error.stack ?? error.message) : "Internal Server Error",
                    },
                });
            }
        }
    );
}) satisfies FastifyPluginAsync;
