/**
 * Transforms a raw compatibility score into a normalized value in the range 0–100.
 *
 * The transformation uses the P5 and P95 percentiles of the raw score distribution
 * as the lower and upper bounds. These percentiles can be regenerated by running:
 *
 * `npx tsx src/scripts/testCompatibilityZodiac.ts`
 *
 * @param rawScore Raw compatibility score.
 * @returns Normalized compatibility score in the range 0–100.
 */
export function normalizeScore(rawScore: number): number {
    // 5th percentile of the raw score distribution.
    // Any value below this will be mapped to 0.
    // const rawMin = 48.8;
    const rawMin = 40;

    // 95th percentile of the raw score distribution.
    // Any value above this will be mapped to 100.
    // const rawMax = 75.7;
    const rawMax = 80;

    // Normalize to the range 0–1.
    const normalized = (rawScore - rawMin) / (rawMax - rawMin);

    // Scale to the range 0–100.
    const score = normalized * 100;

    // Clamp to 0–100 and round to an integer.
    return Math.round(Math.max(0, Math.min(100, score)));
}
