import { LifeArea, Planet } from "../astro";

export interface NormalizerConfig {
    /** Raw sum that maps to a score of 50. */
    median: number;
    /** Raw spread that maps to roughly ±23 score points. Larger = flatter scores. */
    sigma: number;
}

/**
 * Generated by src/scripts/calibrateDailyScore.ts — do not hand-edit.
 *
 * Fitted from 300 charts x 730 days (seed 1592598101) to land the raw
 * distribution on target score percentiles p10 25 / p90 85.
 *
 * These numbers describe THIS rule table. Re-run the calibration whenever
 * src/modules/dailyScore/rules.ts changes.
 */
export const CALIBRATION: Record<LifeArea | "overall", NormalizerConfig> = {
    love: { median: 0.97, sigma: 5.32 },
    career: { median: -1.42, sigma: 5.62 },
    health: { median: -2.24, sigma: 4.55 },
    mood: { median: -1.09, sigma: 4.62 },
    overall: { median: -0.38, sigma: 3.59 },
};

/**
 * How loud each transiting body is for its own norm, fitted only over days on which
 * it actually aspects the chart. Without a per-body fit the Moon would report ~90
 * every day and Neptune ~5, which says nothing about today.
 */
export const PLANET_CALIBRATION: Record<Planet, NormalizerConfig> = {
    sun: { median: 6.79, sigma: 4 },
    moon: { median: 16.43, sigma: 9.79 },
    mercury: { median: 5.39, sigma: 3.25 },
    venus: { median: 6.08, sigma: 3.6 },
    mars: { median: 5.63, sigma: 3.38 },
    jupiter: { median: 3.4, sigma: 2.04 },
    saturn: { median: 3.62, sigma: 2.07 },
    uranus: { median: 2.35, sigma: 1.5 },
    neptune: { median: 2.39, sigma: 1.53 },
    pluto: { median: 2.38, sigma: 1.52 },
};

/**
 * Aspect weight (Σ importance × strength) a RICH day produces — the p90 of the
 * calibration sample. Denominator for `confidence`, so a typical day lands below
 * 1 and only genuinely dense days clamp.
 */
export const EXPECTED_WEIGHT = 27.01;

/** Applied to confidence when the birth time is unknown: no Ascendant, imprecise natal Moon. */
export const NO_BIRTH_TIME_CONFIDENCE_PENALTY = 0.85;

/**
 * Stamped on every row, so a score can be told apart from one fitted to a later
 * table. The suffix hashes the AREA constants only — those are what stored rows
 * depend on. PLANET_CALIBRATION is computed fresh on every request and stored
 * nowhere, so changing it must not mark existing rows stale.
 */
export const CALIBRATION_VERSION = "2026-09-01-02b0a2d7";
