import { AspectRule } from "./types";

/**
 * The astrological knowledge base. SOURCE OF TRUTH — edit by hand.
 *
 * First drafted by src/scripts/generateDailyScoreRules.ts, which is now spent:
 * rules carrying a `hand-authored` comment were written deliberately and a
 * regeneration would destroy them. Texts are still templated and are the next
 * thing to work through.
 *
 * Every (pair, group) combination is covered so no influence is ever silently
 * dropped. Invariants and coverage are enforced by
 * src/scripts/lintDailyScoreRules.ts — run it after editing.
 *
 * Changing any baseImpact, importance or areas value invalidates
 * src/modules/dailyScore/calibration.ts. Re-run the calibration afterwards.
 */
export const ASPECT_RULES: AspectRule[] = [
    {
        pair: ["sun", "sun"],
        group: "conjunction",
        baseImpact: 4.8,
        importance: 1.8,
        areas: { career: 0.4, health: 0.3, mood: 0.3 },
        priority: 5,
        title: "Sun returns",
        description: "Today identity and vitality comes back into sharp focus.",
    },
    {
        pair: ["sun", "sun"],
        group: "harmonious",
        baseImpact: 7.5,
        importance: 1.8,
        areas: { career: 0.4, health: 0.3, mood: 0.3 },
        priority: 5,
        title: "Sun in easy flow",
        description: "Today identity and vitality settles into a comfortable rhythm.",
    },
    {
        pair: ["sun", "sun"],
        group: "challenging",
        baseImpact: -5.3,
        importance: 1.8,
        areas: { career: 0.4, health: 0.3, mood: 0.3 },
        priority: 5,
        title: "Sun under strain",
        description: "Today identity and vitality works against itself and needs a deliberate choice.",
    },
    {
        pair: ["moon", "sun"],
        group: "conjunction",
        baseImpact: 3.6,
        importance: 1.8,
        areas: { mood: 0.4, health: 0.3, career: 0.3 },
        priority: 3,
        title: "Moon meets Sun",
        description: "Today feelings and instinct and identity and vitality fuse into a single, concentrated theme.",
    },
    {
        pair: ["moon", "sun"],
        group: "harmonious",
        baseImpact: 7.3,
        importance: 1.8,
        areas: { mood: 0.4, health: 0.3, career: 0.3 },
        priority: 5,
        title: "Moon and Sun flow together",
        description: "Today feelings and instinct supports identity and vitality without friction.",
    },
    {
        pair: ["moon", "sun"],
        group: "challenging",
        baseImpact: -5.6,
        importance: 1.8,
        areas: { mood: 0.4, health: 0.3, career: 0.3 },
        priority: 5,
        title: "Moon and Sun pull apart",
        description:
            "Today feelings and instinct runs into identity and vitality, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["mercury", "sun"],
        group: "conjunction",
        baseImpact: 3.3,
        importance: 1.63,
        areas: { career: 0.7, mood: 0.2, health: 0.1 },
        priority: 3,
        title: "Mercury meets Sun",
        description:
            "Today thinking and communication and identity and vitality fuse into a single, concentrated theme.",
    },
    {
        pair: ["mercury", "sun"],
        group: "harmonious",
        baseImpact: 6.7,
        importance: 1.63,
        areas: { career: 0.7, mood: 0.2, health: 0.1 },
        priority: 5,
        title: "Mercury and Sun flow together",
        description: "Today thinking and communication supports identity and vitality without friction.",
    },
    {
        pair: ["mercury", "sun"],
        group: "challenging",
        baseImpact: -5.2,
        importance: 1.63,
        areas: { career: 0.7, mood: 0.2, health: 0.1 },
        priority: 4,
        title: "Mercury and Sun pull apart",
        description:
            "Today thinking and communication runs into identity and vitality, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["sun", "venus"],
        group: "conjunction",
        baseImpact: 6.8,
        importance: 1.68,
        areas: { love: 0.7, mood: 0.2, career: 0.1 },
        priority: 5,
        title: "Sun meets Venus",
        description: "Today identity and vitality and affection and pleasure fuse into a single, concentrated theme.",
    },
    {
        pair: ["sun", "venus"],
        group: "harmonious",
        baseImpact: 7.7,
        importance: 1.68,
        areas: { love: 0.7, mood: 0.2, career: 0.1 },
        priority: 5,
        title: "Sun and Venus flow together",
        description: "Today identity and vitality supports affection and pleasure without friction.",
    },
    {
        pair: ["sun", "venus"],
        group: "challenging",
        baseImpact: -4.5,
        importance: 1.68,
        areas: { love: 0.7, mood: 0.2, career: 0.1 },
        priority: 3,
        title: "Sun and Venus pull apart",
        description:
            "Today identity and vitality runs into affection and pleasure, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["mars", "sun"],
        group: "conjunction",
        baseImpact: 3.4,
        importance: 1.65,
        areas: { health: 0.45, career: 0.4, mood: 0.15 },
        priority: 5, // hand-authored: courage and initiative, at the price of friction
        title: "Mars meets Sun",
        description: "Today drive and assertion and identity and vitality fuse into a single, concentrated theme.",
    },
    {
        pair: ["mars", "sun"],
        group: "harmonious",
        baseImpact: 6.1,
        importance: 1.65,
        areas: { health: 0.45, career: 0.4, mood: 0.15 },
        priority: 5,
        title: "Mars and Sun flow together",
        description: "Today drive and assertion supports identity and vitality without friction.",
    },
    {
        pair: ["mars", "sun"],
        group: "challenging",
        baseImpact: -5.9,
        importance: 1.65,
        areas: { health: 0.45, career: 0.4, mood: 0.15 },
        priority: 5,
        title: "Mars and Sun pull apart",
        description:
            "Today drive and assertion runs into identity and vitality, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["jupiter", "sun"],
        group: "conjunction",
        baseImpact: 5.9,
        importance: 1.58,
        areas: { career: 0.65, mood: 0.25, health: 0.1 },
        priority: 5,
        title: "Jupiter meets Sun",
        description: "Today growth and optimism and identity and vitality fuse into a single, concentrated theme.",
    },
    {
        pair: ["jupiter", "sun"],
        group: "harmonious",
        baseImpact: 7.2,
        importance: 1.58,
        areas: { career: 0.65, mood: 0.25, health: 0.1 },
        priority: 5,
        title: "Jupiter and Sun flow together",
        description: "Today growth and optimism supports identity and vitality without friction.",
    },
    {
        pair: ["jupiter", "sun"],
        group: "challenging",
        baseImpact: -4.4,
        importance: 1.58,
        areas: { career: 0.65, mood: 0.25, health: 0.1 },
        priority: 3,
        title: "Jupiter and Sun pull apart",
        description:
            "Today growth and optimism runs into identity and vitality, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["saturn", "sun"],
        group: "conjunction",
        baseImpact: -4.5,
        importance: 1.6,
        areas: { career: 0.6, health: 0.25, mood: 0.15 },
        priority: 5, // hand-authored: obligation on identity, low vitality
        title: "Saturn meets Sun",
        description: "Today structure and limits and identity and vitality fuse into a single, concentrated theme.",
    },
    {
        pair: ["saturn", "sun"],
        group: "harmonious",
        baseImpact: 5.6,
        importance: 1.6,
        areas: { career: 0.6, health: 0.25, mood: 0.15 },
        priority: 4,
        title: "Saturn and Sun flow together",
        description: "Today structure and limits supports identity and vitality without friction.",
    },
    {
        pair: ["saturn", "sun"],
        group: "challenging",
        baseImpact: -6.1,
        importance: 1.6,
        areas: { career: 0.6, health: 0.25, mood: 0.15 },
        priority: 5,
        title: "Saturn and Sun pull apart",
        description:
            "Today structure and limits runs into identity and vitality, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["sun", "uranus"],
        group: "conjunction",
        baseImpact: 2.8,
        importance: 1.5,
        areas: { career: 0.45, mood: 0.4, health: 0.15 },
        priority: 5, // hand-authored: liberation, a sudden change of course
        title: "Sun meets Uranus",
        description:
            "Today identity and vitality and disruption and independence fuse into a single, concentrated theme.",
    },
    {
        pair: ["sun", "uranus"],
        group: "harmonious",
        baseImpact: 5.8,
        importance: 1.5,
        areas: { career: 0.45, mood: 0.4, health: 0.15 },
        priority: 4,
        title: "Sun and Uranus flow together",
        description: "Today identity and vitality supports disruption and independence without friction.",
    },
    {
        pair: ["sun", "uranus"],
        group: "challenging",
        baseImpact: -5.4,
        importance: 1.5,
        areas: { career: 0.45, mood: 0.4, health: 0.15 },
        priority: 3,
        title: "Sun and Uranus pull apart",
        description:
            "Today identity and vitality runs into disruption and independence, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["neptune", "sun"],
        group: "conjunction",
        baseImpact: -2.6,
        importance: 1.5,
        areas: { mood: 0.45, health: 0.35, career: 0.2 },
        priority: 4, // hand-authored: vitality diffused, inspiration without traction
        title: "Neptune meets Sun",
        description:
            "Today imagination and blurred edges and identity and vitality fuse into a single, concentrated theme.",
    },
    {
        pair: ["neptune", "sun"],
        group: "harmonious",
        baseImpact: 5.9,
        importance: 1.5,
        areas: { mood: 0.45, health: 0.35, career: 0.2 },
        priority: 4,
        title: "Neptune and Sun flow together",
        description: "Today imagination and blurred edges supports identity and vitality without friction.",
    },
    {
        pair: ["neptune", "sun"],
        group: "challenging",
        baseImpact: -5.3,
        importance: 1.5,
        areas: { mood: 0.45, health: 0.35, career: 0.2 },
        priority: 3,
        title: "Neptune and Sun pull apart",
        description:
            "Today imagination and blurred edges runs into identity and vitality, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["pluto", "sun"],
        group: "conjunction",
        baseImpact: -4.2,
        importance: 1.53,
        areas: { career: 0.4, mood: 0.4, health: 0.2 },
        priority: 5, // hand-authored: confrontation with power, forced change
        title: "Pluto meets Sun",
        description:
            "Today intensity and transformation and identity and vitality fuse into a single, concentrated theme.",
    },
    {
        pair: ["pluto", "sun"],
        group: "harmonious",
        baseImpact: 5.6,
        importance: 1.53,
        areas: { career: 0.4, mood: 0.4, health: 0.2 },
        priority: 4,
        title: "Pluto and Sun flow together",
        description: "Today intensity and transformation supports identity and vitality without friction.",
    },
    {
        pair: ["pluto", "sun"],
        group: "challenging",
        baseImpact: -5.7,
        importance: 1.53,
        areas: { career: 0.4, mood: 0.4, health: 0.2 },
        priority: 4,
        title: "Pluto and Sun pull apart",
        description:
            "Today intensity and transformation runs into identity and vitality, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["ascendant", "sun"],
        group: "conjunction",
        baseImpact: 2.9,
        importance: 1.75,
        areas: { health: 0.55, career: 0.25, mood: 0.2 },
        priority: 3,
        title: "Ascendant meets Sun",
        description: "Today how you show up and identity and vitality fuse into a single, concentrated theme.",
    },
    {
        pair: ["ascendant", "sun"],
        group: "harmonious",
        baseImpact: 7,
        importance: 1.75,
        areas: { health: 0.55, career: 0.25, mood: 0.2 },
        priority: 5,
        title: "Ascendant and Sun flow together",
        description: "Today how you show up supports identity and vitality without friction.",
    },
    {
        pair: ["ascendant", "sun"],
        group: "challenging",
        baseImpact: -5.6,
        importance: 1.75,
        areas: { health: 0.55, career: 0.25, mood: 0.2 },
        priority: 5,
        title: "Ascendant and Sun pull apart",
        description:
            "Today how you show up runs into identity and vitality, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["moon", "moon"],
        group: "conjunction",
        baseImpact: 2.4,
        importance: 1.8,
        areas: { mood: 0.4, health: 0.3, love: 0.18, career: 0.12 },
        priority: 3,
        title: "Moon returns",
        description: "Today feelings and instinct comes back into sharp focus.",
    },
    {
        pair: ["moon", "moon"],
        group: "harmonious",
        baseImpact: 7,
        importance: 1.8,
        areas: { mood: 0.4, health: 0.3, love: 0.18, career: 0.12 },
        priority: 5,
        title: "Moon in easy flow",
        description: "Today feelings and instinct settles into a comfortable rhythm.",
    },
    {
        pair: ["moon", "moon"],
        group: "challenging",
        baseImpact: -5.9,
        importance: 1.8,
        areas: { mood: 0.4, health: 0.3, love: 0.18, career: 0.12 },
        priority: 5,
        title: "Moon under strain",
        description: "Today feelings and instinct works against itself and needs a deliberate choice.",
    },
    {
        pair: ["mercury", "moon"],
        group: "conjunction",
        baseImpact: 2.2,
        importance: 1.63,
        areas: { career: 0.45, mood: 0.3, love: 0.15, health: 0.1 },
        priority: 2,
        title: "Mercury meets Moon",
        description:
            "Today thinking and communication and feelings and instinct fuse into a single, concentrated theme.",
    },
    {
        pair: ["mercury", "moon"],
        group: "harmonious",
        baseImpact: 6.5,
        importance: 1.63,
        areas: { career: 0.45, mood: 0.3, love: 0.15, health: 0.1 },
        priority: 5,
        title: "Mercury and Moon flow together",
        description: "Today thinking and communication supports feelings and instinct without friction.",
    },
    {
        pair: ["mercury", "moon"],
        group: "challenging",
        baseImpact: -5.4,
        importance: 1.63,
        areas: { career: 0.45, mood: 0.3, love: 0.15, health: 0.1 },
        priority: 4,
        title: "Mercury and Moon pull apart",
        description:
            "Today thinking and communication runs into feelings and instinct, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["moon", "venus"],
        group: "conjunction",
        baseImpact: 5.7,
        importance: 1.68,
        areas: { love: 0.6, mood: 0.3, health: 0.1 },
        priority: 5,
        title: "Moon meets Venus",
        description: "Today feelings and instinct and affection and pleasure fuse into a single, concentrated theme.",
    },
    {
        pair: ["moon", "venus"],
        group: "harmonious",
        baseImpact: 7.4,
        importance: 1.68,
        areas: { love: 0.6, mood: 0.3, health: 0.1 },
        priority: 5,
        title: "Moon and Venus flow together",
        description: "Today feelings and instinct supports affection and pleasure without friction.",
    },
    {
        pair: ["moon", "venus"],
        group: "challenging",
        baseImpact: -4.8,
        importance: 1.68,
        areas: { love: 0.6, mood: 0.3, health: 0.1 },
        priority: 3,
        title: "Moon and Venus pull apart",
        description:
            "Today feelings and instinct runs into affection and pleasure, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["mars", "moon"],
        group: "conjunction",
        baseImpact: -3.4,
        importance: 1.65,
        areas: { health: 0.45, mood: 0.3, love: 0.15, career: 0.1 },
        priority: 5, // hand-authored: emotional heat and reactivity
        title: "Mars meets Moon",
        description: "Today drive and assertion and feelings and instinct fuse into a single, concentrated theme.",
    },
    {
        pair: ["mars", "moon"],
        group: "harmonious",
        baseImpact: 5.9,
        importance: 1.65,
        areas: { health: 0.45, mood: 0.3, love: 0.15, career: 0.1 },
        priority: 5,
        title: "Mars and Moon flow together",
        description: "Today drive and assertion supports feelings and instinct without friction.",
    },
    {
        pair: ["mars", "moon"],
        group: "challenging",
        baseImpact: -6.1,
        importance: 1.65,
        areas: { health: 0.45, mood: 0.3, love: 0.15, career: 0.1 },
        priority: 5,
        title: "Mars and Moon pull apart",
        description:
            "Today drive and assertion runs into feelings and instinct, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["jupiter", "moon"],
        group: "conjunction",
        baseImpact: 4.9,
        importance: 1.58,
        areas: { mood: 0.3, career: 0.35, love: 0.25, health: 0.1 },
        priority: 4,
        title: "Jupiter meets Moon",
        description: "Today growth and optimism and feelings and instinct fuse into a single, concentrated theme.",
    },
    {
        pair: ["jupiter", "moon"],
        group: "harmonious",
        baseImpact: 6.9,
        importance: 1.58,
        areas: { mood: 0.3, career: 0.35, love: 0.25, health: 0.1 },
        priority: 5,
        title: "Jupiter and Moon flow together",
        description: "Today growth and optimism supports feelings and instinct without friction.",
    },
    {
        pair: ["jupiter", "moon"],
        group: "challenging",
        baseImpact: -4.7,
        importance: 1.58,
        areas: { mood: 0.3, career: 0.35, love: 0.25, health: 0.1 },
        priority: 3,
        title: "Jupiter and Moon pull apart",
        description:
            "Today growth and optimism runs into feelings and instinct, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["moon", "saturn"],
        group: "conjunction",
        baseImpact: -2.2,
        importance: 1.6,
        areas: { mood: 0.4, health: 0.3, career: 0.3 },
        priority: 2,
        title: "Moon meets Saturn",
        description: "Today feelings and instinct and structure and limits fuse into a single, concentrated theme.",
    },
    {
        pair: ["moon", "saturn"],
        group: "harmonious",
        baseImpact: 5.4,
        importance: 1.6,
        areas: { mood: 0.4, health: 0.3, career: 0.3 },
        priority: 4,
        title: "Moon and Saturn flow together",
        description: "Today feelings and instinct supports structure and limits without friction.",
    },
    {
        pair: ["moon", "saturn"],
        group: "challenging",
        baseImpact: -6.4,
        importance: 1.6,
        areas: { mood: 0.4, health: 0.3, career: 0.3 },
        priority: 5,
        title: "Moon and Saturn pull apart",
        description:
            "Today feelings and instinct runs into structure and limits, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["moon", "uranus"],
        group: "conjunction",
        baseImpact: -3.2,
        importance: 1.5,
        areas: { mood: 0.3, health: 0.3, love: 0.25, career: 0.15 },
        priority: 5, // hand-authored: sudden mood shifts, restlessness
        title: "Moon meets Uranus",
        description:
            "Today feelings and instinct and disruption and independence fuse into a single, concentrated theme.",
    },
    {
        pair: ["moon", "uranus"],
        group: "harmonious",
        baseImpact: 5.6,
        importance: 1.5,
        areas: { mood: 0.3, health: 0.3, love: 0.25, career: 0.15 },
        priority: 4,
        title: "Moon and Uranus flow together",
        description: "Today feelings and instinct supports disruption and independence without friction.",
    },
    {
        pair: ["moon", "uranus"],
        group: "challenging",
        baseImpact: -5.6,
        importance: 1.5,
        areas: { mood: 0.3, health: 0.3, love: 0.25, career: 0.15 },
        priority: 4,
        title: "Moon and Uranus pull apart",
        description:
            "Today feelings and instinct runs into disruption and independence, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["moon", "neptune"],
        group: "conjunction",
        baseImpact: -2.2,
        importance: 1.5,
        areas: { mood: 0.3, love: 0.3, health: 0.3, career: 0.1 },
        priority: 4, // hand-authored: heightened sensitivity, blurred boundaries
        title: "Moon meets Neptune",
        description:
            "Today feelings and instinct and imagination and blurred edges fuse into a single, concentrated theme.",
    },
    {
        pair: ["moon", "neptune"],
        group: "harmonious",
        baseImpact: 5.7,
        importance: 1.5,
        areas: { mood: 0.3, love: 0.3, health: 0.3, career: 0.1 },
        priority: 4,
        title: "Moon and Neptune flow together",
        description: "Today feelings and instinct supports imagination and blurred edges without friction.",
    },
    {
        pair: ["moon", "neptune"],
        group: "challenging",
        baseImpact: -5.5,
        importance: 1.5,
        areas: { mood: 0.3, love: 0.3, health: 0.3, career: 0.1 },
        priority: 4,
        title: "Moon and Neptune pull apart",
        description:
            "Today feelings and instinct runs into imagination and blurred edges, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["moon", "pluto"],
        group: "conjunction",
        baseImpact: -3.6,
        importance: 1.53,
        areas: { mood: 0.3, love: 0.3, career: 0.25, health: 0.15 },
        priority: 5, // hand-authored: buried feeling surfacing
        title: "Moon meets Pluto",
        description:
            "Today feelings and instinct and intensity and transformation fuse into a single, concentrated theme.",
    },
    {
        pair: ["moon", "pluto"],
        group: "harmonious",
        baseImpact: 5.4,
        importance: 1.53,
        areas: { mood: 0.3, love: 0.3, career: 0.25, health: 0.15 },
        priority: 4,
        title: "Moon and Pluto flow together",
        description: "Today feelings and instinct supports intensity and transformation without friction.",
    },
    {
        pair: ["moon", "pluto"],
        group: "challenging",
        baseImpact: -6,
        importance: 1.53,
        areas: { mood: 0.3, love: 0.3, career: 0.25, health: 0.15 },
        priority: 4,
        title: "Moon and Pluto pull apart",
        description:
            "Today feelings and instinct runs into intensity and transformation, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["ascendant", "moon"],
        group: "conjunction",
        baseImpact: 3,
        importance: 1.75,
        areas: { health: 0.45, mood: 0.3, love: 0.15, career: 0.1 },
        priority: 5, // hand-authored: feelings visible, instinct aligned with presence
        title: "Ascendant meets Moon",
        description: "Today how you show up and feelings and instinct fuse into a single, concentrated theme.",
    },
    {
        pair: ["ascendant", "moon"],
        group: "harmonious",
        baseImpact: 6.7,
        importance: 1.75,
        areas: { health: 0.45, mood: 0.3, love: 0.15, career: 0.1 },
        priority: 5,
        title: "Ascendant and Moon flow together",
        description: "Today how you show up supports feelings and instinct without friction.",
    },
    {
        pair: ["ascendant", "moon"],
        group: "challenging",
        baseImpact: -5.9,
        importance: 1.75,
        areas: { health: 0.45, mood: 0.3, love: 0.15, career: 0.1 },
        priority: 5,
        title: "Ascendant and Moon pull apart",
        description:
            "Today how you show up runs into feelings and instinct, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["mercury", "mercury"],
        group: "conjunction",
        baseImpact: 2,
        importance: 1.45,
        areas: { career: 0.75, mood: 0.25 },
        priority: 1,
        title: "Mercury returns",
        description: "Today thinking and communication comes back into sharp focus.",
    },
    {
        pair: ["mercury", "mercury"],
        group: "harmonious",
        baseImpact: 5.9,
        importance: 1.45,
        areas: { career: 0.75, mood: 0.25 },
        priority: 4,
        title: "Mercury in easy flow",
        description: "Today thinking and communication settles into a comfortable rhythm.",
    },
    {
        pair: ["mercury", "mercury"],
        group: "challenging",
        baseImpact: -5,
        importance: 1.45,
        areas: { career: 0.75, mood: 0.25 },
        priority: 3,
        title: "Mercury under strain",
        description: "Today thinking and communication works against itself and needs a deliberate choice.",
    },
    {
        pair: ["mercury", "venus"],
        group: "conjunction",
        baseImpact: 5.2,
        importance: 1.5,
        areas: { love: 0.55, career: 0.3, mood: 0.15 },
        priority: 3,
        title: "Mercury meets Venus",
        description:
            "Today thinking and communication and affection and pleasure fuse into a single, concentrated theme.",
    },
    {
        pair: ["mercury", "venus"],
        group: "harmonious",
        baseImpact: 6.8,
        importance: 1.5,
        areas: { love: 0.55, career: 0.3, mood: 0.15 },
        priority: 5,
        title: "Mercury and Venus flow together",
        description: "Today thinking and communication supports affection and pleasure without friction.",
    },
    {
        pair: ["mercury", "venus"],
        group: "challenging",
        baseImpact: -4.4,
        importance: 1.5,
        areas: { love: 0.55, career: 0.3, mood: 0.15 },
        priority: 2,
        title: "Mercury and Venus pull apart",
        description:
            "Today thinking and communication runs into affection and pleasure, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["mars", "mercury"],
        group: "conjunction",
        baseImpact: -2.6,
        importance: 1.48,
        areas: { career: 0.55, health: 0.3, mood: 0.15 },
        priority: 4, // hand-authored: fast mind, sharp words
        title: "Mars meets Mercury",
        description: "Today drive and assertion and thinking and communication fuse into a single, concentrated theme.",
    },
    {
        pair: ["mars", "mercury"],
        group: "harmonious",
        baseImpact: 5.4,
        importance: 1.48,
        areas: { career: 0.55, health: 0.3, mood: 0.15 },
        priority: 3,
        title: "Mars and Mercury flow together",
        description: "Today drive and assertion supports thinking and communication without friction.",
    },
    {
        pair: ["mars", "mercury"],
        group: "challenging",
        baseImpact: -5.6,
        importance: 1.48,
        areas: { career: 0.55, health: 0.3, mood: 0.15 },
        priority: 4,
        title: "Mars and Mercury pull apart",
        description:
            "Today drive and assertion runs into thinking and communication, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["jupiter", "mercury"],
        group: "conjunction",
        baseImpact: 4.4,
        importance: 1.4,
        areas: { career: 0.75, mood: 0.25 },
        priority: 2,
        title: "Jupiter meets Mercury",
        description: "Today growth and optimism and thinking and communication fuse into a single, concentrated theme.",
    },
    {
        pair: ["jupiter", "mercury"],
        group: "harmonious",
        baseImpact: 6.3,
        importance: 1.4,
        areas: { career: 0.75, mood: 0.25 },
        priority: 4,
        title: "Jupiter and Mercury flow together",
        description: "Today growth and optimism supports thinking and communication without friction.",
    },
    {
        pair: ["jupiter", "mercury"],
        group: "challenging",
        baseImpact: -4.3,
        importance: 1.4,
        areas: { career: 0.75, mood: 0.25 },
        priority: 2,
        title: "Jupiter and Mercury pull apart",
        description:
            "Today growth and optimism runs into thinking and communication, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["mercury", "saturn"],
        group: "conjunction",
        baseImpact: -2,
        importance: 1.43,
        areas: { career: 0.75, mood: 0.25 },
        priority: 1,
        title: "Mercury meets Saturn",
        description:
            "Today thinking and communication and structure and limits fuse into a single, concentrated theme.",
    },
    {
        pair: ["mercury", "saturn"],
        group: "harmonious",
        baseImpact: 4.9,
        importance: 1.43,
        areas: { career: 0.75, mood: 0.25 },
        priority: 3,
        title: "Mercury and Saturn flow together",
        description: "Today thinking and communication supports structure and limits without friction.",
    },
    {
        pair: ["mercury", "saturn"],
        group: "challenging",
        baseImpact: -5.9,
        importance: 1.43,
        areas: { career: 0.75, mood: 0.25 },
        priority: 4,
        title: "Mercury and Saturn pull apart",
        description:
            "Today thinking and communication runs into structure and limits, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["mercury", "uranus"],
        group: "conjunction",
        baseImpact: 2.6,
        importance: 1.33,
        areas: { career: 0.6, mood: 0.3, health: 0.1 },
        priority: 4, // hand-authored: breakthrough thinking
        title: "Mercury meets Uranus",
        description:
            "Today thinking and communication and disruption and independence fuse into a single, concentrated theme.",
    },
    {
        pair: ["mercury", "uranus"],
        group: "harmonious",
        baseImpact: 5.1,
        importance: 1.33,
        areas: { career: 0.6, mood: 0.3, health: 0.1 },
        priority: 2,
        title: "Mercury and Uranus flow together",
        description: "Today thinking and communication supports disruption and independence without friction.",
    },
    {
        pair: ["mercury", "uranus"],
        group: "challenging",
        baseImpact: -5.1,
        importance: 1.33,
        areas: { career: 0.6, mood: 0.3, health: 0.1 },
        priority: 2,
        title: "Mercury and Uranus pull apart",
        description:
            "Today thinking and communication runs into disruption and independence, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["mercury", "neptune"],
        group: "conjunction",
        baseImpact: -2.4,
        importance: 1.33,
        areas: { career: 0.45, mood: 0.4, health: 0.15 },
        priority: 4, // hand-authored: imagination and fog in equal measure
        title: "Mercury meets Neptune",
        description:
            "Today thinking and communication and imagination and blurred edges fuse into a single, concentrated theme.",
    },
    {
        pair: ["mercury", "neptune"],
        group: "harmonious",
        baseImpact: 5.2,
        importance: 1.33,
        areas: { career: 0.45, mood: 0.4, health: 0.15 },
        priority: 3,
        title: "Mercury and Neptune flow together",
        description: "Today thinking and communication supports imagination and blurred edges without friction.",
    },
    {
        pair: ["mercury", "neptune"],
        group: "challenging",
        baseImpact: -5.1,
        importance: 1.33,
        areas: { career: 0.45, mood: 0.4, health: 0.15 },
        priority: 2,
        title: "Mercury and Neptune pull apart",
        description:
            "Today thinking and communication runs into imagination and blurred edges, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["mercury", "pluto"],
        group: "conjunction",
        baseImpact: -2.8,
        importance: 1.35,
        areas: { career: 0.5, mood: 0.4, health: 0.1 },
        priority: 4, // hand-authored: obsessive, penetrating thought
        title: "Mercury meets Pluto",
        description:
            "Today thinking and communication and intensity and transformation fuse into a single, concentrated theme.",
    },
    {
        pair: ["mercury", "pluto"],
        group: "harmonious",
        baseImpact: 4.9,
        importance: 1.35,
        areas: { career: 0.5, mood: 0.4, health: 0.1 },
        priority: 2,
        title: "Mercury and Pluto flow together",
        description: "Today thinking and communication supports intensity and transformation without friction.",
    },
    {
        pair: ["mercury", "pluto"],
        group: "challenging",
        baseImpact: -5.5,
        importance: 1.35,
        areas: { career: 0.5, mood: 0.4, health: 0.1 },
        priority: 3,
        title: "Mercury and Pluto pull apart",
        description:
            "Today thinking and communication runs into intensity and transformation, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["ascendant", "mercury"],
        group: "conjunction",
        baseImpact: 2.6,
        importance: 1.58,
        areas: { career: 0.5, health: 0.3, mood: 0.2 },
        priority: 4, // hand-authored: articulate and quick in company
        title: "Ascendant meets Mercury",
        description: "Today how you show up and thinking and communication fuse into a single, concentrated theme.",
    },
    {
        pair: ["ascendant", "mercury"],
        group: "harmonious",
        baseImpact: 6.2,
        importance: 1.58,
        areas: { career: 0.5, health: 0.3, mood: 0.2 },
        priority: 5,
        title: "Ascendant and Mercury flow together",
        description: "Today how you show up supports thinking and communication without friction.",
    },
    {
        pair: ["ascendant", "mercury"],
        group: "challenging",
        baseImpact: -5.4,
        importance: 1.58,
        areas: { career: 0.5, health: 0.3, mood: 0.2 },
        priority: 4,
        title: "Ascendant and Mercury pull apart",
        description:
            "Today how you show up runs into thinking and communication, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["venus", "venus"],
        group: "conjunction",
        baseImpact: 8.2,
        importance: 1.55,
        areas: { love: 0.85, mood: 0.15 },
        priority: 5,
        title: "Venus returns",
        description: "Today affection and pleasure comes back into sharp focus.",
    },
    {
        pair: ["venus", "venus"],
        group: "harmonious",
        baseImpact: 7.7,
        importance: 1.55,
        areas: { love: 0.85, mood: 0.15 },
        priority: 5,
        title: "Venus in easy flow",
        description: "Today affection and pleasure settles into a comfortable rhythm.",
    },
    {
        pair: ["venus", "venus"],
        group: "challenging",
        baseImpact: -3.8,
        importance: 1.55,
        areas: { love: 0.85, mood: 0.15 },
        priority: 2,
        title: "Venus under strain",
        description: "Today affection and pleasure works against itself and needs a deliberate choice.",
    },
    {
        pair: ["mars", "venus"],
        group: "conjunction",
        baseImpact: 2.6,
        importance: 1.53,
        areas: { love: 0.6, health: 0.25, mood: 0.15 },
        priority: 1,
        title: "Mars meets Venus",
        description: "Today drive and assertion and affection and pleasure fuse into a single, concentrated theme.",
    },
    {
        pair: ["mars", "venus"],
        group: "harmonious",
        baseImpact: 6.3,
        importance: 1.53,
        areas: { love: 0.6, health: 0.25, mood: 0.15 },
        priority: 5,
        title: "Mars and Venus flow together",
        description: "Today drive and assertion supports affection and pleasure without friction.",
    },
    {
        pair: ["mars", "venus"],
        group: "challenging",
        baseImpact: -5.1,
        importance: 1.53,
        areas: { love: 0.6, health: 0.25, mood: 0.15 },
        priority: 3,
        title: "Mars and Venus pull apart",
        description:
            "Today drive and assertion runs into affection and pleasure, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["jupiter", "venus"],
        group: "conjunction",
        baseImpact: 7.6,
        importance: 1.45,
        areas: { love: 0.65, mood: 0.25, career: 0.1 },
        priority: 5,
        title: "Jupiter meets Venus",
        description: "Today growth and optimism and affection and pleasure fuse into a single, concentrated theme.",
    },
    {
        pair: ["jupiter", "venus"],
        group: "harmonious",
        baseImpact: 7.2,
        importance: 1.45,
        areas: { love: 0.65, mood: 0.25, career: 0.1 },
        priority: 5,
        title: "Jupiter and Venus flow together",
        description: "Today growth and optimism supports affection and pleasure without friction.",
    },
    {
        pair: ["jupiter", "venus"],
        group: "challenging",
        baseImpact: -3.7,
        importance: 1.45,
        areas: { love: 0.65, mood: 0.25, career: 0.1 },
        priority: 2,
        title: "Jupiter and Venus pull apart",
        description:
            "Today growth and optimism runs into affection and pleasure, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["saturn", "venus"],
        group: "conjunction",
        baseImpact: -2.8,
        importance: 1.48,
        areas: { love: 0.65, mood: 0.2, career: 0.15 },
        priority: 4, // hand-authored: duty over pleasure, affection cooled
        title: "Saturn meets Venus",
        description: "Today structure and limits and affection and pleasure fuse into a single, concentrated theme.",
    },
    {
        pair: ["saturn", "venus"],
        group: "harmonious",
        baseImpact: 5.8,
        importance: 1.48,
        areas: { love: 0.65, mood: 0.2, career: 0.15 },
        priority: 4,
        title: "Saturn and Venus flow together",
        description: "Today structure and limits supports affection and pleasure without friction.",
    },
    {
        pair: ["saturn", "venus"],
        group: "challenging",
        baseImpact: -5.3,
        importance: 1.48,
        areas: { love: 0.65, mood: 0.2, career: 0.15 },
        priority: 3,
        title: "Saturn and Venus pull apart",
        description:
            "Today structure and limits runs into affection and pleasure, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["uranus", "venus"],
        group: "conjunction",
        baseImpact: 2.9,
        importance: 1.38,
        areas: { love: 0.65, mood: 0.35 },
        priority: 1,
        title: "Uranus meets Venus",
        description:
            "Today disruption and independence and affection and pleasure fuse into a single, concentrated theme.",
    },
    {
        pair: ["uranus", "venus"],
        group: "harmonious",
        baseImpact: 5.9,
        importance: 1.38,
        areas: { love: 0.65, mood: 0.35 },
        priority: 4,
        title: "Uranus and Venus flow together",
        description: "Today disruption and independence supports affection and pleasure without friction.",
    },
    {
        pair: ["uranus", "venus"],
        group: "challenging",
        baseImpact: -4.6,
        importance: 1.38,
        areas: { love: 0.65, mood: 0.35 },
        priority: 2,
        title: "Uranus and Venus pull apart",
        description:
            "Today disruption and independence runs into affection and pleasure, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["neptune", "venus"],
        group: "conjunction",
        baseImpact: 3.2,
        importance: 1.38,
        areas: { love: 0.7, mood: 0.3 },
        priority: 2,
        title: "Neptune meets Venus",
        description:
            "Today imagination and blurred edges and affection and pleasure fuse into a single, concentrated theme.",
    },
    {
        pair: ["neptune", "venus"],
        group: "harmonious",
        baseImpact: 6,
        importance: 1.38,
        areas: { love: 0.7, mood: 0.3 },
        priority: 4,
        title: "Neptune and Venus flow together",
        description: "Today imagination and blurred edges supports affection and pleasure without friction.",
    },
    {
        pair: ["neptune", "venus"],
        group: "challenging",
        baseImpact: -4.5,
        importance: 1.38,
        areas: { love: 0.7, mood: 0.3 },
        priority: 2,
        title: "Neptune and Venus pull apart",
        description:
            "Today imagination and blurred edges runs into affection and pleasure, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["pluto", "venus"],
        group: "conjunction",
        baseImpact: -2.4,
        importance: 1.4,
        areas: { love: 0.7, mood: 0.3 },
        priority: 4, // hand-authored: obsessive attraction, possessiveness
        title: "Pluto meets Venus",
        description:
            "Today intensity and transformation and affection and pleasure fuse into a single, concentrated theme.",
    },
    {
        pair: ["pluto", "venus"],
        group: "harmonious",
        baseImpact: 5.7,
        importance: 1.4,
        areas: { love: 0.7, mood: 0.3 },
        priority: 3,
        title: "Pluto and Venus flow together",
        description: "Today intensity and transformation supports affection and pleasure without friction.",
    },
    {
        pair: ["pluto", "venus"],
        group: "challenging",
        baseImpact: -4.9,
        importance: 1.4,
        areas: { love: 0.7, mood: 0.3 },
        priority: 3,
        title: "Pluto and Venus pull apart",
        description:
            "Today intensity and transformation runs into affection and pleasure, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["ascendant", "venus"],
        group: "conjunction",
        baseImpact: 5,
        importance: 1.63,
        areas: { love: 0.55, health: 0.3, mood: 0.15 },
        priority: 5,
        title: "Ascendant meets Venus",
        description: "Today how you show up and affection and pleasure fuse into a single, concentrated theme.",
    },
    {
        pair: ["ascendant", "venus"],
        group: "harmonious",
        baseImpact: 7.1,
        importance: 1.63,
        areas: { love: 0.55, health: 0.3, mood: 0.15 },
        priority: 5,
        title: "Ascendant and Venus flow together",
        description: "Today how you show up supports affection and pleasure without friction.",
    },
    {
        pair: ["ascendant", "venus"],
        group: "challenging",
        baseImpact: -4.8,
        importance: 1.63,
        areas: { love: 0.55, health: 0.3, mood: 0.15 },
        priority: 3,
        title: "Ascendant and Venus pull apart",
        description:
            "Today how you show up runs into affection and pleasure, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["mars", "mars"],
        group: "conjunction",
        baseImpact: -3.1,
        importance: 1.5,
        areas: { health: 0.55, career: 0.35, mood: 0.1 },
        priority: 2,
        title: "Mars returns",
        description: "Today drive and assertion comes back into sharp focus.",
    },
    {
        pair: ["mars", "mars"],
        group: "harmonious",
        baseImpact: 4.9,
        importance: 1.5,
        areas: { health: 0.55, career: 0.35, mood: 0.1 },
        priority: 3,
        title: "Mars in easy flow",
        description: "Today drive and assertion settles into a comfortable rhythm.",
    },
    {
        pair: ["mars", "mars"],
        group: "challenging",
        baseImpact: -6.3,
        importance: 1.5,
        areas: { health: 0.55, career: 0.35, mood: 0.1 },
        priority: 5,
        title: "Mars under strain",
        description: "Today drive and assertion works against itself and needs a deliberate choice.",
    },
    {
        pair: ["jupiter", "mars"],
        group: "conjunction",
        baseImpact: 2,
        importance: 1.43,
        areas: { career: 0.5, health: 0.35, mood: 0.15 },
        priority: 1,
        title: "Jupiter meets Mars",
        description: "Today growth and optimism and drive and assertion fuse into a single, concentrated theme.",
    },
    {
        pair: ["jupiter", "mars"],
        group: "harmonious",
        baseImpact: 5.9,
        importance: 1.43,
        areas: { career: 0.5, health: 0.35, mood: 0.15 },
        priority: 4,
        title: "Jupiter and Mars flow together",
        description: "Today growth and optimism supports drive and assertion without friction.",
    },
    {
        pair: ["jupiter", "mars"],
        group: "challenging",
        baseImpact: -4.9,
        importance: 1.43,
        areas: { career: 0.5, health: 0.35, mood: 0.15 },
        priority: 3,
        title: "Jupiter and Mars pull apart",
        description:
            "Today growth and optimism runs into drive and assertion, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["mars", "saturn"],
        group: "conjunction",
        baseImpact: -4.6,
        importance: 1.45,
        areas: { career: 0.5, health: 0.4, mood: 0.1 },
        priority: 2,
        title: "Mars meets Saturn",
        description: "Today drive and assertion and structure and limits fuse into a single, concentrated theme.",
    },
    {
        pair: ["mars", "saturn"],
        group: "harmonious",
        baseImpact: 4.4,
        importance: 1.45,
        areas: { career: 0.5, health: 0.4, mood: 0.1 },
        priority: 2,
        title: "Mars and Saturn flow together",
        description: "Today drive and assertion supports structure and limits without friction.",
    },
    {
        pair: ["mars", "saturn"],
        group: "challenging",
        baseImpact: -6.5,
        importance: 1.45,
        areas: { career: 0.5, health: 0.4, mood: 0.1 },
        priority: 4,
        title: "Mars and Saturn pull apart",
        description:
            "Today drive and assertion runs into structure and limits, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["mars", "uranus"],
        group: "conjunction",
        baseImpact: -2.4,
        importance: 1.35,
        areas: { health: 0.45, career: 0.35, mood: 0.2 },
        priority: 1,
        title: "Mars meets Uranus",
        description:
            "Today drive and assertion and disruption and independence fuse into a single, concentrated theme.",
    },
    {
        pair: ["mars", "uranus"],
        group: "harmonious",
        baseImpact: 4.6,
        importance: 1.35,
        areas: { health: 0.45, career: 0.35, mood: 0.2 },
        priority: 2,
        title: "Mars and Uranus flow together",
        description: "Today drive and assertion supports disruption and independence without friction.",
    },
    {
        pair: ["mars", "uranus"],
        group: "challenging",
        baseImpact: -5.7,
        importance: 1.35,
        areas: { health: 0.45, career: 0.35, mood: 0.2 },
        priority: 3,
        title: "Mars and Uranus pull apart",
        description:
            "Today drive and assertion runs into disruption and independence, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["mars", "neptune"],
        group: "conjunction",
        baseImpact: -2.2,
        importance: 1.35,
        areas: { health: 0.5, mood: 0.3, career: 0.2 },
        priority: 1,
        title: "Mars meets Neptune",
        description:
            "Today drive and assertion and imagination and blurred edges fuse into a single, concentrated theme.",
    },
    {
        pair: ["mars", "neptune"],
        group: "harmonious",
        baseImpact: 4.7,
        importance: 1.35,
        areas: { health: 0.5, mood: 0.3, career: 0.2 },
        priority: 2,
        title: "Mars and Neptune flow together",
        description: "Today drive and assertion supports imagination and blurred edges without friction.",
    },
    {
        pair: ["mars", "neptune"],
        group: "challenging",
        baseImpact: -5.7,
        importance: 1.35,
        areas: { health: 0.5, mood: 0.3, career: 0.2 },
        priority: 3,
        title: "Mars and Neptune pull apart",
        description:
            "Today drive and assertion runs into imagination and blurred edges, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["mars", "pluto"],
        group: "conjunction",
        baseImpact: -3.7,
        importance: 1.38,
        areas: { health: 0.45, career: 0.35, mood: 0.2 },
        priority: 2,
        title: "Mars meets Pluto",
        description:
            "Today drive and assertion and intensity and transformation fuse into a single, concentrated theme.",
    },
    {
        pair: ["mars", "pluto"],
        group: "harmonious",
        baseImpact: 4.4,
        importance: 1.38,
        areas: { health: 0.45, career: 0.35, mood: 0.2 },
        priority: 2,
        title: "Mars and Pluto flow together",
        description: "Today drive and assertion supports intensity and transformation without friction.",
    },
    {
        pair: ["mars", "pluto"],
        group: "challenging",
        baseImpact: -6.1,
        importance: 1.38,
        areas: { health: 0.45, career: 0.35, mood: 0.2 },
        priority: 4,
        title: "Mars and Pluto pull apart",
        description:
            "Today drive and assertion runs into intensity and transformation, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["ascendant", "mars"],
        group: "conjunction",
        baseImpact: -3,
        importance: 1.6,
        areas: { health: 0.65, career: 0.25, mood: 0.1 },
        priority: 5, // hand-authored: physical heat, abrasive presence
        title: "Ascendant meets Mars",
        description: "Today how you show up and drive and assertion fuse into a single, concentrated theme.",
    },
    {
        pair: ["ascendant", "mars"],
        group: "harmonious",
        baseImpact: 5.6,
        importance: 1.6,
        areas: { health: 0.65, career: 0.25, mood: 0.1 },
        priority: 4,
        title: "Ascendant and Mars flow together",
        description: "Today how you show up supports drive and assertion without friction.",
    },
    {
        pair: ["ascendant", "mars"],
        group: "challenging",
        baseImpact: -6.1,
        importance: 1.6,
        areas: { health: 0.65, career: 0.25, mood: 0.1 },
        priority: 5,
        title: "Ascendant and Mars pull apart",
        description:
            "Today how you show up runs into drive and assertion, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["jupiter", "jupiter"],
        group: "conjunction",
        baseImpact: 6.7,
        importance: 1.35,
        areas: { career: 0.55, mood: 0.3, health: 0.15 },
        priority: 4,
        title: "Jupiter returns",
        description: "Today growth and optimism comes back into sharp focus.",
    },
    {
        pair: ["jupiter", "jupiter"],
        group: "harmonious",
        baseImpact: 6.7,
        importance: 1.35,
        areas: { career: 0.55, mood: 0.3, health: 0.15 },
        priority: 4,
        title: "Jupiter in easy flow",
        description: "Today growth and optimism settles into a comfortable rhythm.",
    },
    {
        pair: ["jupiter", "jupiter"],
        group: "challenging",
        baseImpact: -3.6,
        importance: 1.35,
        areas: { career: 0.55, mood: 0.3, health: 0.15 },
        priority: 2,
        title: "Jupiter under strain",
        description: "Today growth and optimism works against itself and needs a deliberate choice.",
    },
    {
        pair: ["jupiter", "saturn"],
        group: "conjunction",
        baseImpact: 2.8,
        importance: 1.38,
        areas: { career: 0.75, mood: 0.15, health: 0.1 },
        priority: 4, // hand-authored: structured growth, sober building
        title: "Jupiter meets Saturn",
        description: "Today growth and optimism and structure and limits fuse into a single, concentrated theme.",
    },
    {
        pair: ["jupiter", "saturn"],
        group: "harmonious",
        baseImpact: 5.4,
        importance: 1.38,
        areas: { career: 0.75, mood: 0.15, health: 0.1 },
        priority: 3,
        title: "Jupiter and Saturn flow together",
        description: "Today growth and optimism supports structure and limits without friction.",
    },
    {
        pair: ["jupiter", "saturn"],
        group: "challenging",
        baseImpact: -5.1,
        importance: 1.38,
        areas: { career: 0.75, mood: 0.15, health: 0.1 },
        priority: 3,
        title: "Jupiter and Saturn pull apart",
        description:
            "Today growth and optimism runs into structure and limits, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["jupiter", "uranus"],
        group: "conjunction",
        baseImpact: 2.3,
        importance: 1.27,
        areas: { career: 0.5, mood: 0.4, health: 0.1 },
        priority: 1,
        title: "Jupiter meets Uranus",
        description:
            "Today growth and optimism and disruption and independence fuse into a single, concentrated theme.",
    },
    {
        pair: ["jupiter", "uranus"],
        group: "harmonious",
        baseImpact: 5.5,
        importance: 1.27,
        areas: { career: 0.5, mood: 0.4, health: 0.1 },
        priority: 3,
        title: "Jupiter and Uranus flow together",
        description: "Today growth and optimism supports disruption and independence without friction.",
    },
    {
        pair: ["jupiter", "uranus"],
        group: "challenging",
        baseImpact: -4.4,
        importance: 1.27,
        areas: { career: 0.5, mood: 0.4, health: 0.1 },
        priority: 2,
        title: "Jupiter and Uranus pull apart",
        description:
            "Today growth and optimism runs into disruption and independence, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["jupiter", "neptune"],
        group: "conjunction",
        baseImpact: 2.5,
        importance: 1.27,
        areas: { mood: 0.55, love: 0.25, career: 0.2 },
        priority: 1,
        title: "Jupiter meets Neptune",
        description:
            "Today growth and optimism and imagination and blurred edges fuse into a single, concentrated theme.",
    },
    {
        pair: ["jupiter", "neptune"],
        group: "harmonious",
        baseImpact: 5.6,
        importance: 1.27,
        areas: { mood: 0.55, love: 0.25, career: 0.2 },
        priority: 3,
        title: "Jupiter and Neptune flow together",
        description: "Today growth and optimism supports imagination and blurred edges without friction.",
    },
    {
        pair: ["jupiter", "neptune"],
        group: "challenging",
        baseImpact: -4.4,
        importance: 1.27,
        areas: { mood: 0.55, love: 0.25, career: 0.2 },
        priority: 2,
        title: "Jupiter and Neptune pull apart",
        description:
            "Today growth and optimism runs into imagination and blurred edges, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["jupiter", "pluto"],
        group: "conjunction",
        baseImpact: 2.6,
        importance: 1.3,
        areas: { career: 0.6, mood: 0.25, health: 0.15 },
        priority: 3, // hand-authored: large ambition, risk of over-reach
        title: "Jupiter meets Pluto",
        description:
            "Today growth and optimism and intensity and transformation fuse into a single, concentrated theme.",
    },
    {
        pair: ["jupiter", "pluto"],
        group: "harmonious",
        baseImpact: 5.3,
        importance: 1.3,
        areas: { career: 0.6, mood: 0.25, health: 0.15 },
        priority: 3,
        title: "Jupiter and Pluto flow together",
        description: "Today growth and optimism supports intensity and transformation without friction.",
    },
    {
        pair: ["jupiter", "pluto"],
        group: "challenging",
        baseImpact: -4.8,
        importance: 1.3,
        areas: { career: 0.6, mood: 0.25, health: 0.15 },
        priority: 2,
        title: "Jupiter and Pluto pull apart",
        description:
            "Today growth and optimism runs into intensity and transformation, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["ascendant", "jupiter"],
        group: "conjunction",
        baseImpact: 4.2,
        importance: 1.53,
        areas: { health: 0.4, career: 0.35, mood: 0.25 },
        priority: 3,
        title: "Ascendant meets Jupiter",
        description: "Today how you show up and growth and optimism fuse into a single, concentrated theme.",
    },
    {
        pair: ["ascendant", "jupiter"],
        group: "harmonious",
        baseImpact: 6.6,
        importance: 1.53,
        areas: { health: 0.4, career: 0.35, mood: 0.25 },
        priority: 5,
        title: "Ascendant and Jupiter flow together",
        description: "Today how you show up supports growth and optimism without friction.",
    },
    {
        pair: ["ascendant", "jupiter"],
        group: "challenging",
        baseImpact: -4.7,
        importance: 1.53,
        areas: { health: 0.4, career: 0.35, mood: 0.25 },
        priority: 3,
        title: "Ascendant and Jupiter pull apart",
        description:
            "Today how you show up runs into growth and optimism, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["saturn", "saturn"],
        group: "conjunction",
        baseImpact: -5.9,
        importance: 1.4,
        areas: { career: 0.6, health: 0.25, mood: 0.15 },
        priority: 4,
        title: "Saturn returns",
        description: "Today structure and limits comes back into sharp focus.",
    },
    {
        pair: ["saturn", "saturn"],
        group: "harmonious",
        baseImpact: 4,
        importance: 1.4,
        areas: { career: 0.6, health: 0.25, mood: 0.15 },
        priority: 2,
        title: "Saturn in easy flow",
        description: "Today structure and limits settles into a comfortable rhythm.",
    },
    {
        pair: ["saturn", "saturn"],
        group: "challenging",
        baseImpact: -6.7,
        importance: 1.4,
        areas: { career: 0.6, health: 0.25, mood: 0.15 },
        priority: 4,
        title: "Saturn under strain",
        description: "Today structure and limits works against itself and needs a deliberate choice.",
    },
    {
        pair: ["saturn", "uranus"],
        group: "conjunction",
        baseImpact: -3.7,
        importance: 1.3,
        areas: { career: 0.5, mood: 0.3, health: 0.2 },
        priority: 2,
        title: "Saturn meets Uranus",
        description:
            "Today structure and limits and disruption and independence fuse into a single, concentrated theme.",
    },
    {
        pair: ["saturn", "uranus"],
        group: "harmonious",
        baseImpact: 4.2,
        importance: 1.3,
        areas: { career: 0.5, mood: 0.3, health: 0.2 },
        priority: 2,
        title: "Saturn and Uranus flow together",
        description: "Today structure and limits supports disruption and independence without friction.",
    },
    {
        pair: ["saturn", "uranus"],
        group: "challenging",
        baseImpact: -5.9,
        importance: 1.3,
        areas: { career: 0.5, mood: 0.3, health: 0.2 },
        priority: 3,
        title: "Saturn and Uranus pull apart",
        description:
            "Today structure and limits runs into disruption and independence, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["neptune", "saturn"],
        group: "conjunction",
        baseImpact: -3.5,
        importance: 1.3,
        areas: { health: 0.4, mood: 0.35, career: 0.25 },
        priority: 2,
        title: "Neptune meets Saturn",
        description:
            "Today imagination and blurred edges and structure and limits fuse into a single, concentrated theme.",
    },
    {
        pair: ["neptune", "saturn"],
        group: "harmonious",
        baseImpact: 4.2,
        importance: 1.3,
        areas: { health: 0.4, mood: 0.35, career: 0.25 },
        priority: 2,
        title: "Neptune and Saturn flow together",
        description: "Today imagination and blurred edges supports structure and limits without friction.",
    },
    {
        pair: ["neptune", "saturn"],
        group: "challenging",
        baseImpact: -5.9,
        importance: 1.3,
        areas: { health: 0.4, mood: 0.35, career: 0.25 },
        priority: 3,
        title: "Neptune and Saturn pull apart",
        description:
            "Today imagination and blurred edges runs into structure and limits, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["pluto", "saturn"],
        group: "conjunction",
        baseImpact: -5,
        importance: 1.33,
        areas: { career: 0.6, mood: 0.25, health: 0.15 },
        priority: 2,
        title: "Pluto meets Saturn",
        description:
            "Today intensity and transformation and structure and limits fuse into a single, concentrated theme.",
    },
    {
        pair: ["pluto", "saturn"],
        group: "harmonious",
        baseImpact: 4,
        importance: 1.33,
        areas: { career: 0.6, mood: 0.25, health: 0.15 },
        priority: 2,
        title: "Pluto and Saturn flow together",
        description: "Today intensity and transformation supports structure and limits without friction.",
    },
    {
        pair: ["pluto", "saturn"],
        group: "challenging",
        baseImpact: -6.3,
        importance: 1.33,
        areas: { career: 0.6, mood: 0.25, health: 0.15 },
        priority: 4,
        title: "Pluto and Saturn pull apart",
        description:
            "Today intensity and transformation runs into structure and limits, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["ascendant", "saturn"],
        group: "conjunction",
        baseImpact: -2.7,
        importance: 1.55,
        areas: { health: 0.5, career: 0.3, mood: 0.2 },
        priority: 2,
        title: "Ascendant meets Saturn",
        description: "Today how you show up and structure and limits fuse into a single, concentrated theme.",
    },
    {
        pair: ["ascendant", "saturn"],
        group: "harmonious",
        baseImpact: 5.1,
        importance: 1.55,
        areas: { health: 0.5, career: 0.3, mood: 0.2 },
        priority: 3,
        title: "Ascendant and Saturn flow together",
        description: "Today how you show up supports structure and limits without friction.",
    },
    {
        pair: ["ascendant", "saturn"],
        group: "challenging",
        baseImpact: -6.4,
        importance: 1.55,
        areas: { health: 0.5, career: 0.3, mood: 0.2 },
        priority: 5,
        title: "Ascendant and Saturn pull apart",
        description:
            "Today how you show up runs into structure and limits, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["ascendant", "uranus"],
        group: "conjunction",
        baseImpact: -2.8,
        importance: 1.45,
        areas: { health: 0.45, mood: 0.4, career: 0.15 },
        priority: 5, // hand-authored: unpredictable presence, bodily restlessness
        title: "Ascendant meets Uranus",
        description: "Today how you show up and disruption and independence fuse into a single, concentrated theme.",
    },
    {
        pair: ["ascendant", "uranus"],
        group: "harmonious",
        baseImpact: 5.3,
        importance: 1.45,
        areas: { health: 0.45, mood: 0.4, career: 0.15 },
        priority: 3,
        title: "Ascendant and Uranus flow together",
        description: "Today how you show up supports disruption and independence without friction.",
    },
    {
        pair: ["ascendant", "uranus"],
        group: "challenging",
        baseImpact: -5.6,
        importance: 1.45,
        areas: { health: 0.45, mood: 0.4, career: 0.15 },
        priority: 3,
        title: "Ascendant and Uranus pull apart",
        description:
            "Today how you show up runs into disruption and independence, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["ascendant", "neptune"],
        group: "conjunction",
        baseImpact: -2.6,
        importance: 1.45,
        areas: { health: 0.5, mood: 0.35, love: 0.15 },
        priority: 4, // hand-authored: blurred self-presentation, low stamina
        title: "Ascendant meets Neptune",
        description: "Today how you show up and imagination and blurred edges fuse into a single, concentrated theme.",
    },
    {
        pair: ["ascendant", "neptune"],
        group: "harmonious",
        baseImpact: 5.4,
        importance: 1.45,
        areas: { health: 0.5, mood: 0.35, love: 0.15 },
        priority: 3,
        title: "Ascendant and Neptune flow together",
        description: "Today how you show up supports imagination and blurred edges without friction.",
    },
    {
        pair: ["ascendant", "neptune"],
        group: "challenging",
        baseImpact: -5.5,
        importance: 1.45,
        areas: { health: 0.5, mood: 0.35, love: 0.15 },
        priority: 3,
        title: "Ascendant and Neptune pull apart",
        description:
            "Today how you show up runs into imagination and blurred edges, and the tension asks for a deliberate choice.",
    },
    {
        pair: ["ascendant", "pluto"],
        group: "conjunction",
        baseImpact: -3.2,
        importance: 1.48,
        areas: { health: 0.4, mood: 0.4, career: 0.2 },
        priority: 5, // hand-authored: identity under pressure
        title: "Ascendant meets Pluto",
        description: "Today how you show up and intensity and transformation fuse into a single, concentrated theme.",
    },
    {
        pair: ["ascendant", "pluto"],
        group: "harmonious",
        baseImpact: 5.1,
        importance: 1.48,
        areas: { health: 0.4, mood: 0.4, career: 0.2 },
        priority: 3,
        title: "Ascendant and Pluto flow together",
        description: "Today how you show up supports intensity and transformation without friction.",
    },
    {
        pair: ["ascendant", "pluto"],
        group: "challenging",
        baseImpact: -5.9,
        importance: 1.48,
        areas: { health: 0.4, mood: 0.4, career: 0.2 },
        priority: 4,
        title: "Ascendant and Pluto pull apart",
        description:
            "Today how you show up runs into intensity and transformation, and the tension asks for a deliberate choice.",
    },
];
